# Generated by Django 3.1.3 on 2020-11-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201110_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
